name: ara_dict
description: "Arabic Lexicons"
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  path: ^1.9.1
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  wakelock_plus: ^1.4.0
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/dictprefixes
    - assets/data/dictstems
    - assets/data/dictsuffixes
    - assets/data/tableab
    - assets/data/tableac
    - assets/data/tablebc
    - assets/data/db.sqlite
    - assets/icons/icon.png

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/amiri/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/amiri/Amiri-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Kitab
      fonts:
        - asset: assets/fonts/kitab/Kitab-Regular.ttf
        - asset: assets/fonts/kitab/Kitab-Bold.ttf
          weight: 700
